# Generated by Django 3.2.2 on 2021-07-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cet',
        ),
        migrations.AddField(
            model_name='category',
            name='cat',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category'),
        ),
    ]
