# Generated by Django 3.2.2 on 2021-07-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_customermodel_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderitems',
            field=models.CharField(max_length=1000),
        ),
    ]
