# Generated by Django 3.2.2 on 2021-07-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_category_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='userid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='orderitems',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
